import { addDecimal, compareDecimal, isDecimal, subtractDecimal } from "./decimal.js";

export type FinancialRecordClass = "EXTERNAL_INFLOW" | "EXTERNAL_OUTFLOW" | "TRADING_OR_PNL_COMPONENT" | "INTERNAL_NON_FLOW" | "UNKNOWN";

export const BITGET_UTA_FINANCIAL_RECORD_CLASSIFICATION: Readonly<Record<string, Exclude<FinancialRecordClass, "UNKNOWN">>> = Object.freeze({
  TRANSFER_IN: "EXTERNAL_INFLOW",
  TRANSFER_OUT: "EXTERNAL_OUTFLOW",
  CONVERSION_UPON_DELISTING: "INTERNAL_NON_FLOW",
  ORDER_DEALT_FROZEN_OUT: "INTERNAL_NON_FLOW",
  ORDER_DEALT_IN: "TRADING_OR_PNL_COMPONENT",
  ORDER_PLF_FEE_OUT: "TRADING_OR_PNL_COMPONENT",
  EXCHANGE_SOURCE_TOKEN_USER_OUT: "INTERNAL_NON_FLOW",
  EXCHANGE_TARGET_TOKEN_USER_IN: "INTERNAL_NON_FLOW",
  OPEN_LONG: "TRADING_OR_PNL_COMPONENT",
  OPEN_SHORT: "TRADING_OR_PNL_COMPONENT",
  BUY_DEAL: "TRADING_OR_PNL_COMPONENT",
  SELL_DEAL: "TRADING_OR_PNL_COMPONENT",
  CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  FORCE_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  FORCE_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  BURST_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  BURST_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  OFFSET_REDUCE_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  OFFSET_REDUCE_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  FORCE_BUY_SSM: "TRADING_OR_PNL_COMPONENT",
  FORCE_SELL_SSM: "TRADING_OR_PNL_COMPONENT",
  BURST_BUY_SSM: "TRADING_OR_PNL_COMPONENT",
  BURST_SELL_SSM: "TRADING_OR_PNL_COMPONENT",
  RISK_LIQ_USER_IN: "TRADING_OR_PNL_COMPONENT",
  RISK_LIQ_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  INTEREST_SETTLEMENT_OUT: "TRADING_OR_PNL_COMPONENT",
  CONTRACT_MAIN_SETTLE_FEE_USER_IN: "TRADING_OR_PNL_COMPONENT",
  CONTRACT_MAIN_SETTLE_FEE_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  BORROW: "INTERNAL_NON_FLOW",
  RESERVE_TRANSFER_IN: "INTERNAL_NON_FLOW",
  RESERVE_TRANSFER_OUT: "INTERNAL_NON_FLOW",
  REPAYMENT: "INTERNAL_NON_FLOW",
  INTEREST_REPAYMENT: "INTERNAL_NON_FLOW",
  LIQ_FUND_OUT: "TRADING_OR_PNL_COMPONENT",
  LIQ_CONVERT_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  LIQ_CONVERT_SYS_IN: "INTERNAL_NON_FLOW",
  LIQ_CONVERT_SYS_OUT: "INTERNAL_NON_FLOW",
  LIQ_CONVERT_USER_IN: "TRADING_OR_PNL_COMPONENT",
  LIQ_TRANSFER_IN: "TRADING_OR_PNL_COMPONENT",
  LIQ_TRANSFER_OUT: "TRADING_OR_PNL_COMPONENT",
  LIQ_FUND_IN: "TRADING_OR_PNL_COMPONENT",
  LIQ_FEE: "TRADING_OR_PNL_COMPONENT",
  LIQ_REPAYMENT: "TRADING_OR_PNL_COMPONENT",
  DELIST_MARGIN_TOKEN_SOURCE_USER_OUT: "INTERNAL_NON_FLOW",
  DELIST_MARGIN_TOKEN_SOURCE_SYS_IN: "INTERNAL_NON_FLOW",
  DELIST_MARGIN_TOKEN_TARGET_SYS_OUT: "INTERNAL_NON_FLOW",
  DELIST_MARGIN_TOKEN_TARGET_USER_IN: "INTERNAL_NON_FLOW",
  CONFISCATE_TOKEN_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  CONFISCATE_TOKEN_SYS_IN: "INTERNAL_NON_FLOW",
  DELIST_SMALL_BALANCE_USER_OUT: "INTERNAL_NON_FLOW",
  DELIST_SMALL_BALANCE_SYS_IN: "INTERNAL_NON_FLOW",
  DELIST_SMALL_LIABILITY_SYS_OUT: "INTERNAL_NON_FLOW",
  DELIST_SMALL_LIABILITY_USER_IN: "INTERNAL_NON_FLOW",
  SMALL_ASSET_SOURCE_TOKEN_USER_OUT: "INTERNAL_NON_FLOW",
  SMALL_ASSET_SOURCE_TOKEN_SYS_IN: "INTERNAL_NON_FLOW",
  SMALL_ASSET_TARGET_TOKEN_SYS_OUT: "INTERNAL_NON_FLOW",
  SMALL_ASSET_TARGET_TOKEN_USER_IN: "INTERNAL_NON_FLOW",
  SMALL_ASSET_FEE_SYS_IN: "INTERNAL_NON_FLOW",
  TRACE_SHARE_BENEFIT_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  TRACE_SHARE_BENEFIT_SYSTEM_IN: "INTERNAL_NON_FLOW",
  TRACE_SHARE_BENEFIT_SYSTEM_OUT: "INTERNAL_NON_FLOW",
  TRACE_SHARE_BENEFIT_USER_IN: "TRADING_OR_PNL_COMPONENT",
  MARGIN_OPEN_LONG: "TRADING_OR_PNL_COMPONENT",
  MARGIN_OPEN_SHORT: "TRADING_OR_PNL_COMPONENT",
  MARIN_BUY_DEAL: "TRADING_OR_PNL_COMPONENT",
  MARIN_SELL_DEAL: "TRADING_OR_PNL_COMPONENT",
  MARGIN_BACK: "INTERNAL_NON_FLOW",
  INCREASE_MARGIN: "INTERNAL_NON_FLOW",
  REDUCE_MARGIN: "INTERNAL_NON_FLOW",
  MARGIN_SETTLE_FEE_USER_IN: "TRADING_OR_PNL_COMPONENT",
  MARGIN_SETTLE_FEE_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  MARGIN_LEVER_ORDER_REFROZEN: "INTERNAL_NON_FLOW",
  MARGIN_LEVER_ORDER_FROZEN: "INTERNAL_NON_FLOW",
  MARGIN_LEVER_POS_IN: "INTERNAL_NON_FLOW",
  FIXED_BACK: "INTERNAL_NON_FLOW",
  FIXED_INCREASE_MARGIN: "INTERNAL_NON_FLOW",
  FIXED_REDUCE_MARGIN: "INTERNAL_NON_FLOW",
  FIXED_LEVER_POS_IN: "INTERNAL_NON_FLOW",
  FIXED_ORDER_PLACE_FROZEN: "INTERNAL_NON_FLOW",
  FIXED_ORDER_FROZEN_RETURN: "INTERNAL_NON_FLOW",
  FIXED_OPEN_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_OPEN_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_BUY_DEAL: "TRADING_OR_PNL_COMPONENT",
  FIXED_SELL_DEAL: "TRADING_OR_PNL_COMPONENT",
  MARGIN_OFFSET_IN_SSM_LONG: "TRADING_OR_PNL_COMPONENT",
  MARGIN_OFFSET_IN_SSM_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_REDUCE_ONLY_OFFSET_IN_SSM_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_REDUCE_ONLY_OFFSET_IN_SSM_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_OFFSET_IN_SSM_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_OFFSET_IN_SSM_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_FORCE_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_FORCE_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_BURST_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_BURST_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_ADL_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_ADL_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  FIXED_RISK_LIQ_USER_IN: "TRADING_OR_PNL_COMPONENT",
  FIXED_RISK_LIQ_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  FIXED_FORCE_BUY_SSM: "TRADING_OR_PNL_COMPONENT",
  FIXED_FORCE_SELL_SSM: "TRADING_OR_PNL_COMPONENT",
  FIXED_BURST_BUY_SSM: "TRADING_OR_PNL_COMPONENT",
  FIXED_BURST_SELL_SSM: "TRADING_OR_PNL_COMPONENT",
  FIXED_DELIVERY_LONG: "TRADING_OR_PNL_COMPONENT",
  FIXED_DELIVERY_SHORT: "TRADING_OR_PNL_COMPONENT",
  DELIVERY_LONG: "TRADING_OR_PNL_COMPONENT",
  DELIVERY_SHORT: "TRADING_OR_PNL_COMPONENT",
  RISK_LIQ_DEFAULT_USER_IN: "TRADING_OR_PNL_COMPONENT",
  FIXED_RISK_LIQ_DEFAULT_USER_IN: "TRADING_OR_PNL_COMPONENT",
  ON_CHAIN_TRANSFER_REFUND: "EXTERNAL_INFLOW",
  ON_CHAIN_TRANSFER_OUT: "EXTERNAL_OUTFLOW",
  MT5_TRANSFER_IN: "EXTERNAL_INFLOW",
  MT5_REFUND_IN: "EXTERNAL_INFLOW",
  MT5_TRANSFER_OUT: "EXTERNAL_OUTFLOW",
  TRACE_LOCK_USER_OUT: "INTERNAL_NON_FLOW",
  TRACE_LOCK_USER_IN: "INTERNAL_NON_FLOW",
  TRACE_TRANSFER_USER_OUT: "EXTERNAL_OUTFLOW",
  TRACE_TRANSFER_USER_IN: "EXTERNAL_INFLOW",
  TRACE_TRANSFER_REFUND_IN: "EXTERNAL_INFLOW",
  FINANCIAL_TRANSFER_OUT: "EXTERNAL_OUTFLOW",
  FINANCIAL_TRANSFER_IN: "EXTERNAL_INFLOW",
  CONVERT_TRANSFER_IN: "INTERNAL_NON_FLOW",
  CONVERT_TRANSFER_OUT: "INTERNAL_NON_FLOW",
  BGPAY_TRANSFER_OUT: "EXTERNAL_OUTFLOW",
  BGPAY_REFUND_IN: "EXTERNAL_INFLOW",
  PAPTRADING_USER_IN: "EXTERNAL_INFLOW",
  PAPTRADING_USER_OUT: "EXTERNAL_OUTFLOW",
  BONUS_GRANT_USER_IN: "EXTERNAL_INFLOW",
  BONUS_EXPIRE_USER_OUT: "EXTERNAL_OUTFLOW",
  BONUS_TRANSFER_USER_OUT: "EXTERNAL_OUTFLOW",
  WITHDRAW_TRANSFER_OUT: "EXTERNAL_OUTFLOW",
  WITHDRAW_TRANSFER_IN: "EXTERNAL_INFLOW",
  REBASE_COIN_SPLIT_OUT: "INTERNAL_NON_FLOW",
  REBASE_COIN_SPLIT_IN: "INTERNAL_NON_FLOW",
  REBASE_COIN_MERGE_OUT: "INTERNAL_NON_FLOW",
  REBASE_COIN_MERGE_IN: "INTERNAL_NON_FLOW",
  RWA_CROSS_SETTLE_FEE_USER_IN: "TRADING_OR_PNL_COMPONENT",
  RWA_CROSS_SETTLE_FEE_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_MAIN_SETTLE_FEE_SYSTEM_IN: "INTERNAL_NON_FLOW",
  RWA_CONTRACT_MAIN_SETTLE_FEE_SYSTEM_OUT: "INTERNAL_NON_FLOW",
  RWA_CONTRACT_MAIN_SETTLE_FEE_SYSTEM_KEEP_IN: "INTERNAL_NON_FLOW",
  RWA_CONTRACT_MAIN_SETTLE_FEE_SYSTEM_KEEP_OUT: "INTERNAL_NON_FLOW",
  RWA_FIXED_SETTLE_FEE_USER_IN: "TRADING_OR_PNL_COMPONENT",
  RWA_FIXED_SETTLE_FEE_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_MAIN_SETTLE_FEE_USER_IN: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_MAIN_SETTLE_FEE_USER_OUT: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_REBASE_USER_OPEN_LONG: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_REBASE_USER_OPEN_SHORT: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_REBASE_USER_CLOSE_LONG: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_REBASE_USER_CLOSE_SHORT: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_REBASE_USER_BUY_IN_SSM: "TRADING_OR_PNL_COMPONENT",
  RWA_CONTRACT_REBASE_USER_SELL_IN_SSM: "TRADING_OR_PNL_COMPONENT",
});

export function classifyFinancialRecordType(type: string): FinancialRecordClass {
  return BITGET_UTA_FINANCIAL_RECORD_CLASSIFICATION[type] ?? "UNKNOWN";
}

export interface FinancialRecordForFlow {
  type: string;
  amount: string | null;
  fee: string | null;
  coin: string | null;
}

export interface FinancialCoverageForFlow {
  complete: boolean;
  lastError: string | null;
}

export interface FinancialRecordCoverageWindow {
  coveredFrom: string;
  coveredThrough: string;
  lastSuccessfulSyncAt: string | null;
  lastError: string | null;
}

export function isFinancialRecordCoverageComplete(
  coverage: FinancialRecordCoverageWindow | null | undefined,
  baselineAt: string | null | undefined,
  now: Date = new Date(),
  lastError: string | null = coverage?.lastError ?? null,
): boolean {
  if (!coverage || !baselineAt || lastError || !coverage.lastSuccessfulSyncAt) return false;
  const baseline = Date.parse(baselineAt);
  const coveredFrom = Date.parse(coverage.coveredFrom);
  const coveredThrough = Date.parse(coverage.coveredThrough);
  const lastSuccessfulSyncAt = Date.parse(coverage.lastSuccessfulSyncAt);
  const freshnessCutoff = now.getTime() - 24 * 60 * 60 * 1000;
  return Number.isFinite(baseline) && Number.isFinite(coveredFrom) && Number.isFinite(coveredThrough) && Number.isFinite(lastSuccessfulSyncAt)
    && coveredFrom <= baseline && coveredThrough >= freshnessCutoff
    && lastSuccessfulSyncAt >= freshnessCutoff && lastSuccessfulSyncAt >= coveredThrough
    && coveredThrough <= now.getTime() + 5 * 60 * 1000;
}

export function calculateNetPnlSinceBaseline(
  currentEquity: string | null | undefined,
  baselineEquity: string | null | undefined,
  flows: { status: "VERIFIED" | "UNVERIFIED"; netExternalInflows: string },
): string {
  if (flows.status !== "VERIFIED" || !isDecimal(currentEquity ?? undefined) || !isDecimal(baselineEquity ?? undefined) || !isDecimal(flows.netExternalInflows)) return "UNAVAILABLE";
  return subtractDecimal(subtractDecimal(currentEquity!, baselineEquity!), flows.netExternalInflows);
}

function absoluteDecimal(value: string): string {
  return value.startsWith("-") || value.startsWith("+") ? value.slice(1) : value;
}

export interface VerifiedExternalFlows {
  status: "VERIFIED" | "UNVERIFIED";
  netExternalInflows: string;
  unknownTypes: string[];
}

export function calculateVerifiedExternalFlows(
  records: readonly FinancialRecordForFlow[],
  categories: readonly FinancialCoverageForFlow[],
  amountsValid = true,
  accountingCoin = "USDT",
): VerifiedExternalFlows {
  const unknownTypes = [...new Set(records.filter((record) => classifyFinancialRecordType(record.type) === "UNKNOWN").map((record) => record.type))].sort();
  const requiredAmountsValid = amountsValid && records.every((record) => {
    const classification = classifyFinancialRecordType(record.type);
    if (classification === "INTERNAL_NON_FLOW") return true;
    if (classification === "UNKNOWN") return false;
    if (!isDecimal(record.amount ?? undefined) || !isDecimal(record.fee ?? "0")) return false;
    if (classification === "TRADING_OR_PNL_COMPONENT") return true;
    return record.coin?.toUpperCase() === accountingCoin.toUpperCase() && compareDecimal(record.amount!, "0") !== 0;
  });
  if (!categories.length || categories.some((category) => !category.complete || category.lastError) || unknownTypes.length || !requiredAmountsValid) {
    return { status: "UNVERIFIED", netExternalInflows: "UNAVAILABLE", unknownTypes };
  }
  let net = "0";
  try {
    for (const record of records) {
      const classification = classifyFinancialRecordType(record.type);
      const magnitude = record.amount ? absoluteDecimal(record.amount) : null;
      if (classification === "EXTERNAL_INFLOW" && magnitude) net = addDecimal(net, magnitude);
      if (classification === "EXTERNAL_OUTFLOW" && magnitude) net = subtractDecimal(net, magnitude);
    }
  } catch {
    return { status: "UNVERIFIED", netExternalInflows: "UNAVAILABLE", unknownTypes };
  }
  return { status: "VERIFIED", netExternalInflows: net, unknownTypes };
}
